name: UnitTest

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: go-version
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: check-mac
      run: go test -v -count=1 -cover  -test.run Test_mac_check ./pkg/fwd

    - name: check-ip
      run: go test -v -count=1 -cover  -test.run Test_ip_check ./pkg/fwd

    - name: check-kv
      run: go test -v -count=1 -cover  -test.run Test_kv_check ./pkg/fwd

    - name: fwd-op
      run: go test -v -count=1 -cover  -test.run Test_fwd_op ./pkg/fwd





